apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lematthe-poi-gateway-app-dev
  annotations:
    argocd/app-name: lematthe-poi-gateway-app-dev
    backstage.io/kubernetes-id: lematthe-poi-gateway-app
    backstage.io/kubernetes-namespace: lematthe
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-gh/lematthe-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/dev-pipelines/ns/lematthe/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/k8s/ns/lematthe/deployments/lematthe-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/#https://github.com/rhdh-gh/lematthe-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/lematthe"
  system: workshop-system-lematthe
  providesApis:
    - gateway-api-lematthe
  consumesApis:
    - backend-api-lematthe
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-lematthe
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/lematthe"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-lematthe
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://lematthe-poi-gateway-app-lematthe.apps.rosa-x4jc7.l07n.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-gh/lematthe-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/lematthe"
  system: workshop-system-lematthe
  definition:
    $text: https://github.com/rhdh-gh/lematthe-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
